version: 2
updates:
  - package-ecosystem: github-actions
    directories: [/, /actions/*]
    schedule:
      interval: weekly
    groups:
      shared-ci:
        patterns: ["nix-forge/ci"]
        group-by: dependency-name
      actions-minor-patch:
        group-by: dependency-name
        patterns: ['*']
        update-types: [minor, patch]
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
